# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: cimg/go

    steps:
      - checkout
      - run: go test -v ./...

workflows:
  test-workflow:
    jobs:
      - test
