# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

commands: # a reusable command with parameters
  restore_and_save_cache:
    steps:
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: go get -v -t -d ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: cimg/go:1.23.4

    steps:
      - checkout
      - restore_and_save_cache
      - run: test -z "$(gofmt -l . | tee /dev/stderr)"
      - run: go vet ./...
      - run: go test -v ./...

workflows:
  test-workflow:
    jobs:
      - test
