// Code generated by go generate; DO NOT EDIT.
package pkg

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"time"
)

// Config represents all configuration options.
type Config struct {
	// Data directory
	DataDir string
	// Node ID
	NodeID string
	// HTTP API bind address
	HTTPAddr string
}

// Forge sets up and parses command-line flags.
func Forge(arguments []string) (*flag.FlagSet, *Config, error) {
	config := &Config{}
	fs := flag.NewFlagSet("name", flag.ExitOnError)
	if len(arguments) <= 0 {
		return nil, nil, fmtError("missing required argument: DataDir")
	}
	fs.StringVar(&config.NodeID, "-node-id", "", "Node ID")
	fs.StringVar(&config.HTTPAddr, "-http-addr", "localhost:4001", "HTTP API bind address")
	if err := fs.Parse(arguments); err != nil {
		return nil, nil, err
	}
	config.DataDir = fs.Arg(0)
	return fs, config, nil
}

func mustParseDuration(d string) time.Duration {
	td, err := time.ParseDuration(d)
	if err != nil {
		panic(err)
	}
	return td
}

func splitString(s, sep string) []string {
	return strings.Split(s, sep)
}

func fmtError(msg string) error {
	return fmt.Errorf(msg)
}

func usage(msg string) {
	fmt.Fprintf(os.Stderr, msg)
}
