// Code generated by go generate; DO NOT EDIT.
package example

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"
	"time"
)

// Config represents all configuration options.
type Config struct {
	// Required path
	Path string
	// Optional label
	Label string
	// First line
	// Second "quoted" line.
	Text string
	// No default.
	Empty string
	// Path!
	File string `filepath:"true"`
	// Enabled?
	Enabled bool
	//
	Count int
	//
	Signed int64
	//
	Unsigned uint64
	//
	Interval time.Duration
	//
	List []string
	//
	Separated []string
	//
	HiddenDuration time.Duration
	//
	HiddenPath string `filepath:"true"`
	//
	HiddenList []string
}

// Forge sets up and parses command-line flags.
func Forge(arguments []string) (*flag.FlagSet, *Config, error) {
	config := &Config{}
	fs := flag.NewFlagSet("quoted \"name\"", flag.ContinueOnError)
	fs.StringVar(&config.Text, "text", "C:\\new\\path \"quoted\"", "First line\nSecond \"quoted\" line.")
	fs.StringVar(&config.Empty, "empty", "", "No default.")
	fs.StringVar(&config.File, "file", "", "Path!")
	fs.BoolVar(&config.Enabled, "enabled", false, "Enabled?")
	fs.IntVar(&config.Count, "count", 0, "")
	fs.Int64Var(&config.Signed, "signed", 0, "")
	fs.Uint64Var(&config.Unsigned, "unsigned", 0, "")
	fs.DurationVar(&config.Interval, "interval", mustParseDuration("0s"), "")
	var tmpList string
	fs.StringVar(&tmpList, "list", "", "")
	var tmpSeparated string
	fs.StringVar(&tmpSeparated, "separated", "a\\b", "")
	fs.Usage = func() {
		usage("Usage:\n  example [flags] <path> [label]\n")
		fs.PrintDefaults()
	}
	if err := fs.Parse(arguments); err != nil {
		return nil, nil, err
	}
	if fs.NArg() <= 0 {
		return nil, nil, fmtError("missing required argument: Path")
	}
	config.Path = fs.Arg(0)
	config.Label = fs.Arg(1)
	config.List = splitString(tmpList, ",")
	config.Separated = splitString(tmpSeparated, "\\")
	return fs, config, nil
}

func mustParseDuration(d string) time.Duration {
	td, err := time.ParseDuration(d)
	if err != nil {
		panic(err)
	}
	return td
}

func splitString(s, sep string) []string {
	if s == "" {
		return nil
	}
	return strings.Split(s, sep)
}

func fmtError(msg string) error {
	return errors.New(msg)
}

func usage(msg string) {
	fmt.Fprintf(os.Stderr, "%s", msg)
}
