// Code generated by go generate; DO NOT EDIT.
package pkg

import (
	"flag"
)

// Config represents all configuration options.
type Config struct {
	// Node ID
	NodeID string
	// HTTP API bind address
	HTTPAddr string
}

// Forge sets up and parses command-line flags.
func Forge(arguments []string) (*flag.FlagSet, *Config, error) {
	config := &Config{}
	fs := flag.NewFlagSet("name", flag.ExitOnError)
	fs.StringVar(&config.NodeID, "-node-id", "", "Node ID")
	fs.StringVar(&config.HTTPAddr, "-http-addr", "localhost:4001", "HTTP API bind address")
	if err := fs.Parse(arguments); err != nil {
		return nil, nil, err
	}
	return fs, config, nil
}
